export const ENV = {
  NODE_ENV: process.env.NODE_ENV,

  CHF_CONFIG_PATH: process.env.CHF_CONFIG_PATH,
  CHF_DEFAULT_DB_URL: process.env.CHF_DEFAULT_DB_URL,
  CHF_DEFAULT_DB_USERNAME: process.env.CHF_DEFAULT_DB_USERNAME,
  CHF_DEFAULT_DB_PASSWORD: process.env.CHF_DEFAULT_DB_PASSWORD,
  CHF_DEFAULT_DB_NAME: process.env.CHF_DEFAULT_DB_NAME,
};